//
// Created by David Nedrow on 2021-10-27.
//

#ifndef SWIFTNCURSES_SWIFTNCURSES_NCURSES_H
#define SWIFTNCURSES_SWIFTNCURSES_NCURSES_H

#include <ncurses.h>

#endif //SWIFTNCURSES_SWIFTNCURSES_NCURSES_H
